import { createClient } from './client';

export const COURSE_STATUSES = ['planning', 'in_progress', 'completed'] as const;
export type CourseStatus = (typeof COURSE_STATUSES)[number];

/** Row shape of `public.courses`. */
export interface Course {
  id: string;
  learner_id: string;
  title: string;
  description: string | null;
  source_type: string;
  skill_track_id: string | null;
  planned_lesson_count: number | null;
  planned_minutes_per_lesson: number | null;
  estimated_total_minutes: number | null;
  status: CourseStatus;
  created_at: string;
  updated_at: string;
}

/**
 * Create a structured course's plan row. Throws (rather than the
 * silent-null pattern used for ad-hoc session tracking) when there's no
 * signed-in user — Structured Course mode is an explicit choice the learner
 * made, so a failure here should surface, not be swallowed. Only lesson 1's
 * content is generated by the caller right after this; lessons 2..N are
 * created lazily as the learner reaches them (see lib/courses/lessons.ts).
 */
export async function createCourse(input: {
  title: string;
  description?: string | null;
  plannedLessonCount: number;
  plannedMinutesPerLesson: number;
}): Promise<Course> {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error('Not signed in');

  const { data, error } = await supabase
    .from('courses')
    .insert({
      learner_id: user.id,
      title: input.title,
      description: input.description ?? null,
      source_type: 'prompt',
      planned_lesson_count: input.plannedLessonCount,
      planned_minutes_per_lesson: input.plannedMinutesPerLesson,
      estimated_total_minutes: input.plannedLessonCount * input.plannedMinutesPerLesson,
    })
    .select('*')
    .single();
  if (error) throw error;
  return data as Course;
}

/** Fetch one course by id, for the signed-in learner's own course (RLS-scoped). */
export async function fetchCourse(courseId: string): Promise<Course | null> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('courses')
    .select('*')
    .eq('id', courseId)
    .maybeSingle();
  if (error) throw error;
  return (data as Course | null) ?? null;
}

export async function updateCourseStatus(courseId: string, status: CourseStatus): Promise<void> {
  const supabase = createClient();
  const { error } = await supabase.from('courses').update({ status }).eq('id', courseId);
  if (error) throw error;
}
